-- AlterTable
ALTER TABLE "Container"
ALTER COLUMN "mrn" DROP NOT NULL,
ALTER COLUMN "stop" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "terminalName" DROP NOT NULL,
ALTER COLUMN "lastRefreshTime" SET DEFAULT CURRENT_TIMESTAMP;
